FROM gcr.io/deeplearning-platform-release/tf2-gpu.2-6

ARG GITHUB_OWNER_ARG
ENV GITHUB_OWNER=${GITHUB_OWNER_ARG}

ARG GITHUB_REPO_ARG
ENV GITHUB_REPO=${GITHUB_REPO_ARG}

ARG GITHUB_WORKFLOW_ARG
ENV GITHUB_WORKFLOW=${GITHUB_WORKFLOW_ARG}

ARG GITHUB_TOKEN_ARG
ENV GITHUB_TOKEN=${GITHUB_TOKEN_ARG}

ARG GCS_BUCKET_ARG
ENV GCS_BUCKET=${GCS_BUCKET_ARG}

ARG MODEL_TAG_ARG
ENV MODEL_TAG=${MODEL_TAG_ARG}


WORKDIR /src

ADD train.py /src
ADD utils.py /src