name: Start Deploy Pipeline

on:
  workflow_dispatch:
    inputs:
      units:
        description: 'units'     
        required: true
      optimizer:
        description: 'optimizer'     
        required: true

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set env
      run: |
        echo ${{ github.run_number }}
        echo "TAG=`echo ${{ github.run_number }}`" >> $GITHUB_ENV
        
    - name: Docker Build & Push Action
      uses: mr-smithers-excellent/docker-build-push@v5.6
      with:
        image: mnist_classifier_training
        tags: ${{ env.TAG }}
        registry: ghcr.io
        dockerfile: Dockerfile
        directory: .
        username: ${{ github.repository_owner }}
        password: ${{ secrets.SECRET_TOKEN }}
        buildArgs: GCS_BUCKET_ARG=${{ secrets.GCS_BUCKET }}, MODEL_TAG_ARG=${{ env.TAG }}, GITHUB_OWNER_ARG=KIMnJANG, GITHUB_REPO_ARG=deploy-pipeline, GITHUB_WORKFLOW_ARG=bentoml.yml, GITHUB_TOKEN_ARG=${{ secrets.SECRET_TOKEN}}
        addLatest: true
    
    - name: Checkout mlops_mnist_config
      uses: actions/checkout@v2
      with:
        token: ${{ secrets.SECRET_TOKEN}}
        repository: KIMnJANG/deploy-pipeline
        path: deploy-pipeline
        
    - name: set hyper parameter
      run: |
        cd deploy-pipeline/kustomize/overlays/dev
        kustomize edit set image ghcr.io/kimnjang/mnist_classifier_training:${{ env.TAG }}
        echo $(jq '.[].value = ["--deploy", "True", "--optimizer", "${{ github.event.inputs.optimizer }}", "--units", "${{ github.event.inputs.units }}"]' training-job-patch.json) > training-job-patch.json
        git config --global user.name ${{ github.repository_owner }}
        git config --global user.email "iam@junil.kim"
        git commit -am 'Publish new version ${GITHUB_SHA} to dev'
        git push || echo 'no changes'
